config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/terms_of_service', to: 'static_pages#terms_of_service'
  get '/contact_us', to: 'static_pages#contact_us'
  get '/location_trouble', to: 'static_pages#location_trouble'
  get '/auth0_icon', to: 'static_pages#auth0_icon'
  get '/lets_login', to: 'static_pages#lets_login'
  get '/progressive_web_apps', to: 'static_pages#progressive_web_apps'
  get '/links', to: 'static_pages#links'

  get '/auth/:provider/callback', to: 'auth0#callback'
  get '/auth/failure', to: 'auth0#failure'
  get '/logout', to: 'auth0#logout'

  resources :posts do
    resources :bookmarks, only: %i[create destroy]
    member do
      get 'nearby_posts'
    end

    collection do
      get 'latest_posts'
    end
  end

  resources :distance_calculators, only: [:index]
  resources :movement_methods, only: [:index]
  resources :clothing_suggestions, only: [:index]

  namespace :mypage do
    get '/', to: 'favorites#index'

    resources :posts, only: [:index]
    resources :bookmark_posts, only: [:index]
    resource :settings, only: %i[show update destroy]
  end

  resources :developer_notices

  get '*unmatched_route', to: 'static_pages#top'
end

app/controllers/mypage/base_controller.rb
module Mypage
  class BaseController < ApplicationController
    layout 'mypage/layouts/mypage'
    before_action :require_login
  end
end

app/controllers/mypage/bookmark_posts_controller.rb
module Mypage
  class BookmarkPostsController < Mypage::BaseController
    def index
      @posts = current_user.bookmarks_posts.order(created_at: :desc).page(params[:page])
    end
  end
end

app/controllers/mypage/posts_controller.rb
module Mypage
  class PostsController < Mypage::BaseController
    def index
      @posts = current_user.posts.order(created_at: :desc).page(params[:page])
    end
  end
end

app/controllers/mypage/settings_controller.rb
module Mypage
  class SettingsController < Mypage::BaseController
    before_action :set_user, only: %i[show update destroy]

    def show; end

    def update
      @user.assign_attributes(user_params)
      # 保存前にupdated_at以外に変更があるかチェック
      changes_without_updated_at = @user.changed - ['updated_at']

      if validate_avatar(user_params[:avatar]) && @user.save
        @user.touch # 初期設定モーダルであとで設定を押すとupdated_atのみ更新される（２回目のモーダルが出なくなる）

        # updated_at以外に変更があった場合のみフラッシュメッセージを表示
        flash[:success] = 'ユーザーを更新しました' if changes_without_updated_at.any?

        # リダイレクト処理
        if request.referer == mypage_settings_url
          redirect_to mypage_settings_path
        else
          redirect_to request.referer || root_path
        end

      else
        render :show
      end
    end

    def destroy
      @user.posts.update_all(user_id: nil)
      @user.destroy
      flash[:info] = 'ユーザーを削除しました'
      reset_session
      redirect_to :root
    end

    private

    def set_user
      @user = current_user
    end

    def user_params
      params.require(:user).permit(:name, :avatar)
    end

    def validate_avatar(avatar)
      return true if avatar.blank?

      result = Vision.image_analysis(avatar)

      unless result
        flash[:error] = '不適切な画像です'
        return false
      end

      true
    end
  end
end

app/views/mypage/shared/_post.html.erb
<div class="card w-full lg:w-[820px] bg-base-100 shadow-xl mb-5 flex flex-wrap">
  <div class="card-body w-full">
    <div class="flex justify-end">
      <% if current_user.bookmark?(post) && request.path == mypage_bookmark_posts_path %>
        <%= button_to post_bookmark_path(post_id: post.id, id: current_user.bookmarks.find_by(post_id: post.id)), method: :delete, class: "btn btn-ghost btn-sm" do %>
          <p class="text-xl text-yellow-500">★</p>
        <% end %>
      <% end %>
    </div>
    <div class="flex flex-wrap justify-center md:justify-start">
      <div class="w-44 md:mr-10">
        <% if post.images.present? %>
          <% first_image = post.images.first %>
          <%= image_tag first_image.to_s, class: "aspect-[3/2] object-cover" %>
        <% end %>
      </div>
      <div class="flex flex-col w-auto">
        <h4 class="card-title my-5">
          <%= link_to post.title, post_path(post) %>
        </h4>
        <p class="mb-5">
          <%= post.address %>
        </p>
      </div>
    </div>
    <% if current_user == post.user %>
      <div class="flex flex-wrap justify-end">
        <%= link_to "編集", edit_post_path(post), class: "btn mr-2" %>
        <%= button_to "削除", post_path(post), method: :delete, class: "btn", id: "delete-button" %>
      </div>
    <% end %>
  </div>
</div>