config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/terms_of_service', to: 'static_pages#terms_of_service'
  get '/contact_us', to: 'static_pages#contact_us'
  get '/location_trouble', to: 'static_pages#location_trouble'
  get '/auth0_icon', to: 'static_pages#auth0_icon'
  get '/lets_login', to: 'static_pages#lets_login'
  get '/progressive_web_apps', to: 'static_pages#progressive_web_apps'
  get '/links', to: 'static_pages#links'

  get '/auth/:provider/callback', to: 'auth0#callback'
  get '/auth/failure', to: 'auth0#failure'
  get '/logout', to: 'auth0#logout'

  resources :posts do
    resources :bookmarks, only: %i[create destroy]
    member do
      get 'nearby_posts'
    end

    collection do
      get 'latest_posts'
    end
  end

  resources :distance_calculators, only: [:index]
  resources :movement_methods, only: [:index]
  resources :clothing_suggestions, only: [:index]

  namespace :mypage do
    get '/', to: 'favorites#index'

    resources :posts, only: [:index]
    resources :bookmark_posts, only: [:index]
    resource :settings, only: %i[show update destroy]
  end

  resources :developer_notices

  get '*unmatched_route', to: 'static_pages#top'
end

app/views/shared/_before_login_header.html.erb
<div class="navbar bg-base-100 z-10">
  <div class="flex-1">
    <%= link_to root_path, class: "btn btn-ghost h-auto w-[150px] sm:w-[170px]" do %>
      <%= image_tag('logo.webp') %>
    <% end %>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1 sm:mr-5 flex items-center">
      <%= link_to clothing_suggestions_path do %>
        <!-- スマホサイズより大きい場合に表示 -->
        <li class="hidden sm:block">
          <p>
            現在の北海道：
            <% if @weather %>
              <%= @weather[:temp] %>°C
              <%= image_tag(weather_icon(@weather[:condition]), class: "w-6 h-6") %>
            <% else %>
              天気を取得できません
            <% end %>
          </p>
        </li>
      <% end %>
      <li>
        <%= button_to 'ログイン', '/auth/auth0', method: :post %>
      </li>
      <li>
        <details class="relative">
          <summary>
            メニュー
          </summary>
          <ul class="bg-base-100 rounded-t-none w-[132px] absolute right-0 sm:right-auto">
            <li><%= link_to "投稿一覧", posts_path %></li>
            <li><%= link_to "新着の投稿", latest_posts_posts_path %></li>
            <li><%= link_to "新規投稿", new_post_path %></li>
            <hr class="my-2 h-0.5 border-t-0 bg-neutral-100 opacity-100 dark:opacity-50" />
            <li><%= link_to "移動時間計算", distance_calculators_path %></li>
            <li><%= link_to "行き方検索", movement_methods_path %></li>
            <li><%= link_to "服装の提案", clothing_suggestions_path %></li>
            <hr class="my-2 h-0.5 border-t-0 bg-neutral-100 opacity-100 dark:opacity-50" />
            <li><%= link_to "観光サイト", links_path %></li>
          </ul>
        </details>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div role="alert" class="alert alert-warning">
    <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
    </svg>
    <div class="flex flex-col items-start">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <% case message_type %>
  <% when 'info' %>
    <div role="alert" class="alert alert-info">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-current shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
      <span><%= message %></span>
    </div>
  <% when 'success' %>
    <div role="alert" class="alert alert-success">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
      <span><%= message %></span>
    </div>
  <% when 'warning' %>
    <div role="alert" class="alert alert-warning">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" /></svg>
      <span><%= message %></span>
    </div>
  <% when 'error' %>
    <div role="alert" class="alert alert-error">
      <svg xmlns="http://www.w3.org/2000/svg" class="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
      <span><%= message %></span>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-6 bg-base-200 rounded">
  <nav class="flex flex-wrap justify-center">
    <%= link_to "お知らせ", developer_notices_path, class: "btn btn-ghost btn-sm" %>
    <%= link_to "お問い合わせ", contact_us_path, class: "btn btn-ghost btn-sm" %>
    <%= link_to "アプリダウンロード方法", progressive_web_apps_path, class: "btn btn-ghost btn-sm" %>
    <%= link_to "利用規約", terms_of_service_path, class: "btn btn-ghost btn-sm" %>
    <%= link_to "プライバシーポリシー", privacy_policy_path, class: "btn btn-ghost btn-sm" %>
  </nav>
  <aside>
    <p>© 2024 - ezo travel</p>
  </aside>
</footer>

app/views/shared/_header.html.erb
<div class="navbar bg-base-100 z-10">
  <div class="flex-1">
    <%= link_to root_path, class: "btn btn-ghost h-auto w-[150px] sm:w-[170px]" do %>
      <%= image_tag('logo.webp') %>
    <% end %>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1 sm:mr-5 flex items-center">
      <%= link_to clothing_suggestions_path do %>
        <!-- スマホサイズより大きい場合に表示 -->
        <li class="hidden sm:block">
          <p>
            現在の北海道：
            <% if @weather %>
              <%= @weather[:temp] %>°C
              <%= image_tag(weather_icon(@weather[:condition]), class: "w-6 h-6") %>
            <% else %>
              天気を取得できません
            <% end %>
          </p>
        </li>
        <!-- スマホサイズの場合に表示 -->
        <li class="block sm:hidden">
          <p>
            <% if @weather[:temp] %>
              <%= @weather[:temp] %>°C
            <% else %>
              気温を取得できません
            <% end %>
          </p>
        </li>
      <% end %>
      <li>
        <details class="relative">
          <summary>
            メニュー
          </summary>
          <ul class="bg-base-100 rounded-t-none w-[132px] absolute right-0 sm:right-auto">
            <li><%= link_to "投稿一覧", posts_path %></li>
            <li><%= link_to "新着の投稿", latest_posts_posts_path %></li>
            <li><%= link_to "新規投稿", new_post_path %></li>
            <hr class="my-2 h-0.5 border-t-0 bg-neutral-100 opacity-100 dark:opacity-50" />
            <li><%= link_to "移動時間計算", distance_calculators_path %></li>
            <li><%= link_to "行き方検索", movement_methods_path %></li>
            <li><%= link_to "服装の提案", clothing_suggestions_path %></li>
            <hr class="my-2 h-0.5 border-t-0 bg-neutral-100 opacity-100 dark:opacity-50" />
            <li><%= link_to "観光サイト", links_path %></li>
            <hr class="my-2 h-0.5 border-t-0 bg-neutral-100 opacity-100 dark:opacity-50" />
            <li><%= link_to "マイページ", mypage_bookmark_posts_path %></li>
            <li><%= button_to "ログアウト", logout_path, method: :get %></li>
          </ul>
        </details>
      </li>
    </ul>
  </div>
</div>

app/views/shared/_modal.html.erb
<dialog id="modal" class="modal">
  <div class="modal-box sm:w-[500px]">
    <div class="my-7">
      <p class="text-center">
        ご登録ありがとうございます<br>
        プロフィールを設定してください
      </p>
      <p class="text-center text-xs mt-2">
        いつでもマイページから設定することができます
      </p>
    <div>
    <div class="mt-10">
      <%= form_with(model: @user, url: mypage_settings_path, local: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="flex flex-col">
          <div id="preview-avatar" class="flex flex-wrap justify-center">
            <% if @user.avatar.present? %>
              <%= image_tag @user.avatar.to_s, class: "w-32 h-auto rounded-full" %>
            <% else %>
              <%= image_tag ("default.webp"), class: "w-32 h-auto rounded-full" %>
            <% end %>
          </div>
          <div class="flex flex-col mt-5">
            <%= f.label :avatar %>
            <%= f.file_field :avatar, class: "file-input file-input-bordered file-input-info w-full", id: "avatar-input" %>
            <span class="text-xs text-right mt-1">ファイル形式：jpeg、jpg、png</span>
          </div>
        </div>
        <div class="flex flex-col">
          <%= f.label :name %>
          <%= f.text_field :name, placeholder: "ニックネームを入力してください", class: "input input-bordered w-full", autocomplete: "off" %>
        </div>
        <div class="flex justify-center mt-5">
          <%= f.submit id: "modal-submit-button", class: "btn btn-info" %>
        </div>
        <div class="hidden flex justify-center mt-4" id="loading">
          <div class="text-sm">送信中</div>
          <div class="ml-0.5 loading loading-dots loading-xs"></div>
        </div>

        <div class="flex justify-center sm:justify-end mt-5">
          <%= f.submit "あとで設定する",id: "setup-later", class: "btn" %>
        </div>
      <% end %>
    </div>
  </div>
</dialog>

<script>
  window.addEventListener('DOMContentLoaded', (event) => {
    document.getElementById('modal').showModal();
  });
</script>