config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/terms_of_service', to: 'static_pages#terms_of_service'
  get '/contact_us', to: 'static_pages#contact_us'
  get '/location_trouble', to: 'static_pages#location_trouble'
  get '/auth0_icon', to: 'static_pages#auth0_icon'
  get '/lets_login', to: 'static_pages#lets_login'
  get '/progressive_web_apps', to: 'static_pages#progressive_web_apps'
  get '/links', to: 'static_pages#links'

  get '/auth/:provider/callback', to: 'auth0#callback'
  get '/auth/failure', to: 'auth0#failure'
  get '/logout', to: 'auth0#logout'

  resources :posts do
    resources :bookmarks, only: %i[create destroy]
    member do
      get 'nearby_posts'
    end

    collection do
      get 'latest_posts'
    end
  end

  resources :distance_calculators, only: [:index]
  resources :movement_methods, only: [:index]
  resources :clothing_suggestions, only: [:index]

  namespace :mypage do
    get '/', to: 'favorites#index'

    resources :posts, only: [:index]
    resources :bookmark_posts, only: [:index]
    resource :settings, only: %i[show update destroy]
  end

  resources :developer_notices

  get '*unmatched_route', to: 'static_pages#top'
end

app/controllers/mypage/base_controller.rb
module Mypage
  class BaseController < ApplicationController
    layout 'mypage/layouts/mypage'
    before_action :require_login
  end
end

app/controllers/mypage/bookmark_posts_controller.rb
module Mypage
  class BookmarkPostsController < Mypage::BaseController
    def index
      @posts = current_user.bookmarks_posts.order(created_at: :desc).page(params[:page])
    end
  end
end

app/controllers/mypage/posts_controller.rb
module Mypage
  class PostsController < Mypage::BaseController
    def index
      @posts = current_user.posts.order(created_at: :desc).page(params[:page])
    end
  end
end

app/controllers/mypage/settings_controller.rb
module Mypage
  class SettingsController < Mypage::BaseController
    before_action :set_user, only: %i[show update destroy]

    def show; end

    def update
      @user.assign_attributes(user_params)
      # 保存前にupdated_at以外に変更があるかチェック
      changes_without_updated_at = @user.changed - ['updated_at']

      if validate_avatar(user_params[:avatar]) && @user.save
        @user.touch # 初期設定モーダルであとで設定を押すとupdated_atのみ更新される（２回目のモーダルが出なくなる）

        # updated_at以外に変更があった場合のみフラッシュメッセージを表示
        flash[:success] = 'ユーザーを更新しました' if changes_without_updated_at.any?

        # リダイレクト処理
        if request.referer == mypage_settings_url
          redirect_to mypage_settings_path
        else
          redirect_to request.referer || root_path
        end

      else
        render :show
      end
    end

    def destroy
      @user.posts.update_all(user_id: nil)
      @user.destroy
      flash[:info] = 'ユーザーを削除しました'
      reset_session
      redirect_to :root
    end

    private

    def set_user
      @user = current_user
    end

    def user_params
      params.require(:user).permit(:name, :avatar)
    end

    def validate_avatar(avatar)
      return true if avatar.blank?

      result = Vision.image_analysis(avatar)

      unless result
        flash[:error] = '不適切な画像です'
        return false
      end

      true
    end
  end
end

app/views/mypage/layouts/mypage.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>えぞとらべる | マイページ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag('favicon.ico') %>
    <link rel="manifest" href="/manifest.json">
    <link href="https://fonts.googleapis.com/css2?family=Zen+Maru+Gothic:wght@400&display=swap" rel="stylesheet">

    <!-- Metaタグ -->
    <%= show_meta_tags %>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-7L8Z99PCBX"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-7L8Z99PCBX');
    </script>
  </head>

  <body class="flex flex-col min-h-screen font-main">
    <%= render 'shared/header' %>

    <div class="collapse collapse-arrow bg-base-200">
      <input type="checkbox" id="mypage-menu" />
      <div class="collapse-title font-bold flex justify-center">
        &emsp;&emsp;&ensp;マイページメニュー
      </div>
      <div class="collapse-content">
        <ul class="menu items-center">
          <li><%= link_to "お気に入りの投稿", mypage_bookmark_posts_path %></li>
          <li><%= link_to "自分の投稿", mypage_posts_path %></li>
          <li><%= link_to "プロフィール設定", mypage_settings_path %></li>
        </ul>
      </div>
    </div>

    <div class="flex-grow">
      <%= render 'shared/flash_message' %>
      <%= yield %>
    </div>

    <%= render 'shared/footer' %>

  </body>
</html>