config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'

  get '/privacy_policy', to: 'static_pages#privacy_policy'
  get '/terms_of_service', to: 'static_pages#terms_of_service'
  get '/contact_us', to: 'static_pages#contact_us'
  get '/location_trouble', to: 'static_pages#location_trouble'
  get '/auth0_icon', to: 'static_pages#auth0_icon'
  get '/lets_login', to: 'static_pages#lets_login'
  get '/progressive_web_apps', to: 'static_pages#progressive_web_apps'
  get '/links', to: 'static_pages#links'

  get '/auth/:provider/callback', to: 'auth0#callback'
  get '/auth/failure', to: 'auth0#failure'
  get '/logout', to: 'auth0#logout'

  resources :posts do
    resources :bookmarks, only: %i[create destroy]
    member do
      get 'nearby_posts'
    end

    collection do
      get 'latest_posts'
    end
  end

  resources :distance_calculators, only: [:index]
  resources :movement_methods, only: [:index]
  resources :clothing_suggestions, only: [:index]

  namespace :mypage do
    get '/', to: 'favorites#index'

    resources :posts, only: [:index]
    resources :bookmark_posts, only: [:index]
    resource :settings, only: %i[show update destroy]
  end

  resources :developer_notices

  get '*unmatched_route', to: 'static_pages#top'
end

app/models/post.rb
class Post < ApplicationRecord
  geocoded_by :address
  after_validation :geocode
  mount_uploaders :images, ImageUploader

  has_and_belongs_to_many :tags
  has_and_belongs_to_many :seasons

  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :users, through: :bookmarks

  validates :title, presence: true, length: { maximum: 255 }
  validates :address, presence: true, uniqueness: true
  validates :body, length: { maximum: 300 }
  validates :images, length: { maximum: 3, message: 'は3枚までしかアップロードできません' }

  validate :validate_address
  validate :validate_hokkaido
  validate :must_have_tags

  def validate_address
    geocoded = Geocoder.search(address)
    return if geocoded&.first&.coordinates.present?

    errors.add(:address, 'が存在しません')
  end

  def validate_hokkaido
    return if address.include?('北海道')

    errors.add(:base, '北海道の住所を入力してください')
  end

  def must_have_tags
    errors.add(:base, 'タグを1つ以上選択してください') unless tags.present?
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[title body] # 検索可能な属性を指定してください
  end

  def self.ransackable_associations(_auth_object = nil)
    %w[tags user] # 検索可能な関連付けを指定してください
  end

  # フリーワード検索でひらがなとカタカナを区別しないためのメソッド
  def self.normalize_search_string(search_string)
    hiragana = search_string.tr('ァ-ン', 'ぁ-ん') # カタカナをひらがなに変換
    katakana = search_string.tr('ぁ-ん', 'ァ-ン') # ひらがなをカタカナに変換
    "#{hiragana} #{katakana}" # カタカナとひらがなの両方を含む形で返す
  end
end

app/controllers/mypage/posts_controller.rb
module Mypage
  class PostsController < Mypage::BaseController
    def index
      @posts = current_user.posts.order(created_at: :desc).page(params[:page])
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: %i[new create]
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authorize_user, only: %i[edit update destroy]

  def index
    if params[:q].present? && params[:q][:title_or_body_cont].present?
      search_param = Post.normalize_search_string(params[:q][:title_or_body_cont])
      # OR条件で検索するために`_any`を使って配列を渡す
      @q = Post.ransack(title_or_body_cont_any: search_param.split(/[[:space:]]+/))
    else
      @q = Post.ransack(params[:q])
    end

    @posts = if params[:tag_id].present?
               tag = Tag.includes(:posts).find_by(id: params[:tag_id])
               tag.present? ? tag.posts : []
             elsif params[:season_id].present?
               season = Season.includes(:posts).find_by(id: params[:season_id])
               season.present? ? season.posts : []
             else
               @q.result.includes(:tags, :seasons)
             end
    @filtering_active = params[:q].present? || params[:tag_id].present? || params[:season_id].present?
  end

  def show; end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if validate_images(post_params[:images]) && @post.save
      flash[:success] = '投稿が作成されました'
      redirect_to posts_path
    else
      render :new
    end
  end

  def update
    params[:post].delete(:images) if params[:post][:images].all?(&:blank?)

    @post.attributes = post_params

    if validate_images(post_params[:images]) && @post.save
      flash[:success] = '投稿が更新されました'
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = '投稿が削除されました'

    if request.referer == mypage_posts_url
      redirect_to mypage_posts_path
    else
      redirect_to posts_path
    end
  end

  def latest_posts
    @posts = Post.order(created_at: :desc).limit(20)
  end

  def nearby_posts
    post = Post.find(params[:id])
    nearby_posts = post.nearbys(params[:distance]).limit(3)

    render json: nearby_posts.as_json(only: %i[id title latitude longitude images])
  end

  private

  def post_params
    params.require(:post).permit(:title, :address, :body, :images_cache, tag_ids: [], season_ids: [], images: [])
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def authorize_user
    return if current_user && (current_user == @post.user || current_user.admin?)

    flash[:error] = '権限がありません'
    redirect_to posts_path
  end

  def validate_images(images)
    return true if images.blank? || images.all?(&:blank?)

    cleaned_images = images.reject(&:blank?) # imagesに空の値が含まれる場合はimage_analysisメソッドでエラーが起こるため除去
    inappropriate_images = []

    cleaned_images.each do |image|
      result = Vision.image_analysis(image)
      inappropriate_images << image unless result
    end

    if inappropriate_images.any?
      flash[:error] = '不適切な画像が含まれています'
      return false
    end

    true
  end
end

app/views/posts/_bookmark_button.html.erb
<% if current_user.bookmark?(post) %>
  <%= button_to post_bookmark_path(post_id: post.id, id: current_user.bookmarks.find_by(post_id: post.id)), method: :delete, class: "btn btn-ghost btn-sm" do %>
    <p class="text-xl text-yellow-500">★</p>
  <% end %>
<% else %>
  <%= button_to post_bookmarks_path(post_id: post.id), method: :post, class: "btn btn-ghost btn-sm" do %>
    <p class="text-xl">☆</p>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<div class="min-h-screen">
  <div class="flex justify-center my-14">
    <div class="card w-[800px] shadow-xl">
      <div class="card-body p-10">
        <%= form_with(model: post, local: true) do |f| %>
          <div class="mb-8 flex justify-center">
            <% if f.object.new_record? %>
              <div class="text-xl font-bold">新規投稿</div>
            <% else %>
              <div class="text-xl font-bold">投稿編集</div>
            <% end %>
          </div>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="flex flex-col mt-5">
            <div class="flex justify-between">
              <%= f.label :title, for: "Title" %>

              <div class="dropdown dropdown-end">
                <div tabindex="0" role="button" class="btn btn-xs sm:btn-ghost flex justify-center">
                  <%= image_tag 'yubi.webp', class: "w-5 h-5" %>
                  <p>スポット名がわからない方</p>
                </div>
                <div tabindex="0" class="card compact dropdown-content z-[1] shadow bg-base-100 rounded-box w-64">
                  <div tabindex="0" class="card-body">
                    <p>投稿したい場所に関するキーワード入力してください</p>
                    <span class="text-xs mt-1">新しいタブで検索結果が表示されます</span>
                    <%= text_field_tag :query, nil, placeholder: 'キーワードを入力して検索', id: 'search-query', autocomplete: "off", class: "input input-bordered" %>
                    <%= button_tag "検索", type: 'button', id: 'search-btn', class: "btn btn-sm btn-info" %>
                  </div>
                </div>
              </div>
            </div>

            <%= f.text_field :title, id: "Title", placeholder: "スポット名や市町村名を入力してください", class: "input input-bordered w-full", autocomplete: "off" %>
            <span class="text-xs text-right mt-1">必須</span>
          </div>
          <div class="flex flex-col mt-5">
            <%= f.label :address, for: "Address" %>
            <%= f.text_field :address, id: "Address", placeholder: "候補から選択すると住所が自動で入力されます", class: "input input-bordered w-full", autocomplete: "off" %>
            <span class="text-xs text-right mt-1">必須（同じ住所は投稿できません）</span>
          </div>
          <div class="flex flex-col mt-5">
            <%= f.label :body %>
            <%= f.text_area :body, placeholder: "どういう部分がおすすめか教えてください", class: "input input-bordered w-full textarea", autocomplete: "off" %>
            <span id="charCount" class="text-xs text-right mt-1">300文字まで</span>
          </div>
          <div class="flex flex-col mt-5">
            <div class="flex flex-col">
              <%= f.label :images %>
              <%= f.file_field :images, multiple: true, class: "file-input file-input-bordered file-input-info w-full", id: "post-images-input" %>
              <%= f.hidden_field :images_cache %>
              <span class="text-xs text-right mt-1">3枚まで（ファイル形式：jpeg、jpg、png、heic）</span>
            </div>
            <div id="preview-post-images" class="flex flex-wrap justify-center">
              <% if post.images.present? %>
                <% post.images.each do |image| %>
                  <%= image_tag image.to_s, class: "w-1/3 h-auto object-contain m-2" %>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="flex flex-col mt-5">
            <p>タグ</p>
            <div class="flex flex-wrap">
              <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :title, { checked: @post.tag_ids }, { multiple: true }) do |tag| %>
                <label class="px-4 my-2 w-1/2 sm:w-1/3">
                  <%= tag.check_box(class: 'hidden', data: { behavior: 'tag-checkbox' }) %>
                  <button type="button" class="btn btn-sm w-full <%= 'bg-success text-white' if @post.tag_ids.include?(tag.value.to_i) %>" data-behavior="tag-button"><%= tag.text %></button>
                </label>
              <% end %>
            </div>
            <span class="text-xs text-right mt-1">タグを1つ以上選択してください</span>
          </div>
          <div class="flex flex-col mt-5">
            <p>ベストシーズン（任意）</p>
            <div class="flex flex-wrap">
              <%= f.collection_check_boxes(:season_ids, Season.all, :id, :title, { checked: @post.season_ids }, { multiple: true }) do |season| %>
                <label class="px-2 my-2 w-1/4 sm:w-1/6">
                  <%= season.check_box(class: 'hidden', data: { behavior: 'season-checkbox' }) %>
                  <button type="button" class="btn btn-sm w-full <%= 'bg-success text-white' if @post.season_ids.include?(season.value.to_i) %>" data-behavior="season-button"><%= season.text %></button>
                </label>
              <% end %>
            </div>
          </div>
          <div class="flex justify-center mt-7">
            <%= f.submit (f.object.new_record? ? "投稿する" : "更新する"), id: "submit-button", class: "btn btn-info" %>
          </div>
          <div class="hidden flex justify-center mt-4" id="loading">
            <div class="text-sm">送信中</div>
            <div class="ml-0.5 loading loading-dots loading-xs"></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_API_KEY"] %>&libraries=places&callback=initialize"></script>

app/views/posts/_post.html.erb
<div class="card w-full lg:w-[820px] bg-base-100 shadow-xl mb-5 flex flex-wrap">
  <div class="card-body w-full">
    <div class="flex flex-wrap justify-center items-center md:justify-start">
      <div class="w-44 md:mr-10">
        <% if post.images.present? %>
          <% first_image = post.images.first %>
          <%= image_tag first_image.to_s, class: "aspect-[3/2] object-cover" %>
        <% end %>
      </div>
      <div class="flex flex-col w-auto sm:w-[350px] lg:w-[480px]">
        <h4 class="card-title my-5">
          <%= link_to post.title, post_path(post) %>
        </h4>
        <p class="mb-1">
          <%= post.address %>
        </p>
        <% if post.body %>
          <p class="mb-5">
            <%= truncate(post.body, length: 30) %>
          </p>
        <% end %>
      </div>
    </div>
    <div class="flex flex-wrap justify-end">
      <%= post.created_at.strftime('%Y/%m/%d') %>
    </div>
  </div>
</div>

app/views/posts/_search.html.erb
<%= search_form_for @q, url: url do |f| %>
  <%= f.search_field :title_or_body_cont, class: 'input input-bordered w-2/3 sm:w-1/2', placeholder: 'ここに入力（例：ラーメン）', autocomplete: "off", value: params.dig(:q, :title_or_body_cont) %>
  <%= f.submit '検索', class: 'btn btn-info' %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form', { post: @post } %>

app/views/posts/latest_posts.html.erb
<div class="flex flex-col p-5">
  <div class="m-5 flex justify-center">
    <%= image_tag 'kira.webp', class: "w-6 h-6" %>
    <div class="text-xl font-bold mx-2">新着の投稿</div>
    <%= image_tag 'kira.webp', class: "w-6 h-6" %>
  </div>
  <div class="my-5 flex justify-center">
    <p class="hidden sm:block">新着の投稿20選です！気になる投稿のタイトルを押すと詳細が見られます</p>
    <p class="text-center block sm:hidden">新着の投稿20選です！<br>投稿のタイトルを押すと詳細が見られます</p>
  </div>
  <div class="mx-auto mt-5">
    <% if @posts.present? %>
      <% @posts.each do |post| %>
        <%= render 'posts/post', post: post %>
      <% end %>
    <% else %>
      <p class="p-10">投稿がありません</p>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= render 'form', { post: @post } %>

app/views/posts/show.html.erb
<% if @post.images.present? %>
  <% assign_meta_tags title: @post.title, image: @post.images.first.url %>
<% else %>
  <% assign_meta_tags title: @post.title %>
<% end %>

<div class="min-h-screen">
  <div class="flex justify-center my-14">
    <div class="card w-full sm:w-[800px] shadow-xl">
      <div class="card-body p-10">
        <div class="flex items-center justify-between">
          <div>
            <% if request.referer.present? %>
              <% referer_path = URI.parse(request.referer).path %>
              <% if referer_path == mypage_bookmark_posts_path %>
                <%= link_to "＜ 戻る", mypage_bookmark_posts_path %>
              <% elsif referer_path == mypage_posts_path %>
                <%= link_to "＜ 戻る", mypage_posts_path %>
              <% elsif referer_path == latest_posts_posts_path %>
                <%= link_to "＜ 戻る", latest_posts_posts_path %>
              <% else %>
                <%= link_to "＜ 戻る", posts_path %>
              <% end %>
            <% else %>
              <%= link_to "＜ 戻る", posts_path %>
            <% end %>
          </div>
          <div>
            <% if logged_in? %>
              <%= render 'bookmark_button', { post: @post } %>
            <% end %>
          </div>
        </div>
        <div class="my-7">
          <div class="flex justify-center">
            <% if @post.images.present? %>
              <div class="carousel">
                <div id="slide1" class="carousel-item relative w-full justify-center items-center">
                  <%= image_tag @post.images.first.to_s, width: 500%>
                  <% if @post.images.second.present? %>
                    <div class="absolute flex justify-end transform -translate-y-1/2 right-2.5 top-1/2">
                      <a href="#slide2" class="btn btn-circle glass btn-sm">❯</a>
                    </div>
                  <% end %>
                </div>
                <% if @post.images.second.present? %>
                  <div id="slide2" class="carousel-item relative w-full justify-center items-center">
                    <%= image_tag @post.images.second.to_s, width: 500 %>
                    <div class="absolute flex justify-between transform -translate-y-1/2 left-2.5 right-2.5 top-1/2">
                      <a href="#slide1" class="btn btn-circle glass btn-sm">❮</a>
                      <% if @post.images.third.present? %>
                        <a href="#slide3" class="btn btn-circle glass btn-sm">❯</a>
                      <% end %>
                    </div>
                  </div>
                <% end %>
                <% if @post.images.third.present? %>
                  <div id="slide3" class="carousel-item relative w-full justify-center items-center">
                    <%= image_tag @post.images.third.to_s, width: 500 %>
                    <div class="absolute flex justify-start transform -translate-y-1/2 left-2.5 top-1/2">
                      <a href="#slide2" class="btn btn-circle glass btn-sm">❮</a>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="px-1 sm:px-28">
          <div>
            <p class="text-3xl font-bold mb-2"><%= @post.title %></p>
          </div>
          <div>
            <% @post.tags.each do |tag| %>
              <span class="badge badge-info gap-2"><%= tag.title %></span>
            <% end %>
            <% @post.seasons.each do |season| %>
              <span class="badge badge-warning gap-2"><%= season.title %></span>
            <% end %>
          </div>
          <div class="mt-9">
            <p class="font-bold">所在地</p>
            <p><%= @post.address %></p>
          </div>
          <% if @post.body.present? %>
            <div class="mt-8">
              <p class="font-bold">おすすめポイント</p>
              <p><%= @post.body %></p>
            </div>
          <% end %>
          <div class="mt-8">
            <p class="font-bold">アクセス</p>
            <div class="mt-2 flex justify-center">
              <div id="map" class="w-full h-60 sm:w-96 sm:h-96"></div>
            </div>
          </div>
          <div class="mt-8">
            <div class="mt-7 flex items-center">
              <div>移動時間：</div>
              <div id="calculate-route">
                <div class="btn">位置情報を許可する</div>
              </div>
            </div>
            <%= link_to "※位置情報取得ボタンが押せない場合はこちら", location_trouble_path, class: " mt-1 btn btn-xs btn-ghost" %>
          </div>
          <div class="mt-12">
            <p class="font-bold">近くのおすすめスポット</p>
            <div id="nearby-posts" class="mt-2 flex flex-wrap justify-center"></div>
          </div>
          <div class="mt-8 flex justify-between items-center">
            <div class="flex items-center">
              <% if @post.user.present? %>
                <div>
                  <% if @post.user.avatar? %>
                    <%= image_tag @post.user.avatar.url, class: "rounded-full w-10" %>
                  <% else %>
                    <%= image_tag ("default.webp"), class: "rounded-full w-10" %>
                  <% end %>
                </div>
                <div class="ml-5">
                  <%= @post.user.name %>
                </div>
              <% else %>
                <div>
                  <%= image_tag ("default.webp"), class: "rounded-full w-10" %>
                </div>
                <div class="ml-5">
                  <p>退会したユーザー</p>
                </div>
              <% end %>
            </div>

            <div class="space-x-2 flex items-center">
              <p class="text-xs hidden sm:block">SNSで共有</p>
              <div>
                <%= link_to "https://twitter.com/intent/tweet?url=#{ request.url }&text=#{@post.title}を見つけたよ！%0A&hashtags=えぞとらべる&hashtags=北海道&hashtags=北海道旅行&hashtags=#{@post.title.gsub(/[[:space:]]+/, '')}", target: '_blank' do %>
                  <%= image_tag ("sns_x.webp"), class: "rounded-full w-10" %>
                <% end %>
              </div>
              <div class="w-10">
                <%= link_to "https://social-plugins.line.me/lineit/share?url=#{ request.url }&text=#{@post.title}を見つけたよ！", target: '_blank' do %>
                  <%= image_tag ("sns_line.webp"), class: "rounded-full w-10" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <% if current_user && (current_user == @post.user || current_user.admin?) %>
          <div class="mt-8 flex justify-end">
            <%= link_to "編集", edit_post_path(@post), class: "btn mr-2" %>
            <%= button_to "削除", post_path(@post), method: :delete, class: "btn", id: "delete-button" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  // ミニマップの表示
  function initMap() {
    const mapElement = document.getElementById('map');

    const mapOptions = {
      center: { lat: <%= @post.latitude %>, lng: <%= @post.longitude %> },
      zoom: 16,
      mapTypeControl: false,
      fullscreenControl: false,
      keyboardShortcuts: false
    };

    const map = new google.maps.Map(mapElement, mapOptions);

    const marker = new google.maps.Marker({
      position: { lat: <%= @post.latitude %>, lng: <%= @post.longitude %> },
      map: map,
      title: '<%= @post.title %>'
    });
  }


  // 道民用の移動時間表示
  document.addEventListener('DOMContentLoaded', function() {
    // ユーザーの位置情報取得の許可状態を確認
    if ('geolocation' in navigator) {
      navigator.permissions.query({name: 'geolocation'}).then(function(result) {
        if (result.state === 'granted') {
          // 許可されている場合は自動的に移動時間を計算
          navigator.geolocation.getCurrentPosition(function(position) {
            const originLat = position.coords.latitude;
            const originLng = position.coords.longitude;
            calculateRoute(originLat, originLng, destinationLat, destinationLng);
          });
        } else {
          // 許可されていない場合は位置情報取得確認のボタンを表示
          document.getElementById('calculate-route').style.display = 'block';
        }
      });
    } else {
      alert('位置情報が取得できませんでした');
    }
  });

  const destinationLat = <%= @post.latitude %>;
  const destinationLng = <%= @post.longitude %>;

  document.getElementById('calculate-route').addEventListener('click', function() {
    // ユーザーに位置情報取得
    if ('geolocation' in navigator) {
      navigator.geolocation.getCurrentPosition(function(position) {
        const originLat = position.coords.latitude;
        const originLng = position.coords.longitude;

        // Google Maps APIを使って移動時間を計算するための関数を呼び出し
        calculateRoute(originLat, originLng, destinationLat, destinationLng);
      });
    } else {
      alert('位置情報が取得できませんでした');
    }
  });

  function calculateRoute(originLat, originLng, destinationLat, destinationLng) {
    const directionsService = new google.maps.DirectionsService();

    const request = {
      origin: {lat: originLat, lng: originLng},
      destination: {lat: destinationLat, lng: destinationLng},
      travelMode: 'DRIVING'
    };

    directionsService.route(request, function(response, status) {
      if (status == 'OK') {
        // 移動時間を取得して表示
        const travelTime = response.routes[0].legs[0].duration.text;
        document.getElementById('calculate-route').innerHTML = '現在地からおよそ 車で' + travelTime;
      } else {
        alert('移動時間を取得できませんでした');
      }
    });
  }


  // 近くのおすすめスポット表示機能
  document.addEventListener("DOMContentLoaded", function() {
    const postId = <%= @post.id %>;
    const postLatitude = <%= @post.latitude %>;
    const postLongitude = <%= @post.longitude %>;

    fetch(`/posts/${postId}/nearby_posts?distance=20`) // distance=検索したい距離(km)
      .then(response => {
        if (!response.ok) {
          throw new Error("Network response was not ok");
        }
        return response.json();
      })
      .then(data => {
        const nearbyPostsContainer = document.getElementById('nearby-posts');

        if (data.length === 0) {
          const noPostsMessage = document.createElement('p');
          noPostsMessage.textContent = '見つかりませんでした';
          noPostsMessage.className = 'px-2 text-neutral-content';
          nearbyPostsContainer.appendChild(noPostsMessage);
        } else {
          data.forEach(post => {
            // カード要素（カード全体をリンクに）
            const card = document.createElement('a');
            card.className = 'card bg-base-100 shadow-xl w-[200px] h-[150px] m-4 pb-4 flex items-center justify-center';
            card.href = `/posts/${post.id}`;

            // 投稿に写真があれば画像を表示
            if (post.images && post.images.length > 0) {
              const img = document.createElement('img');
              img.src = post.images[0].url; // 最初の画像のURLを設定
              img.className = 'rounded-t-2xl aspect-[16/9] object-cover'; // Tailwind CSSのクラス
              card.appendChild(img); // 画像をカードに追加
            }

            // 投稿のタイトルを表示
            const title = document.createElement('h3');
            title.textContent = post.title;
            title.className = 'text-xs p-2';
            card.appendChild(title);
            nearbyPostsContainer.appendChild(card);
          });
        }
      })
      .catch(error => {
        console.log(error);
        console.error('There has been a problem with your fetch operation:', error);
      });
  });
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_API_KEY"] %>&callback=initMap"></script>